In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'D:\Portfolio\DS\Home Credit\Credit_home-analyst\data\raw\dazone_sample_test.csv')

In [4]:
df = df.sort_values(by='customer_id').reset_index(drop=True)
df.head()

,Unnamed: 0,customer_id,treatment,cash_sign_30d,card_sign_30d,min_sign_vol,avg_sign_vol,cnt_month_from_last_appl,cli_age,cli_job,...,max_cntr_len_fi_12m,amt_terminated_loan_12m,cnt_terminated_loan_12m,cnt_month_over3_credit_card_6m,cnt_noinsurance_loan_24m,cnt_earlyterminated_cash,cnt_earlyterminted_pos,cnt_inbound_tls_12m,cnt_month_from_first_transaction,cnt_month_from_last_transaction
0,6825,6,cash,NaN,NaN,6924000.0,8805000.0,40,25,WORKER,...,NaN,0.0,0.0,1.0,0.0,1,0,0.0,NaN,NaN
1,10307,13,cash,NaN,NaN,3048000.0,3054000.0,119,32,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
2,23987,23,card,NaN,NaN,9029000.0,8744000.0,48,39,OTHER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
3,0,35,cash,NaN,NaN,6061000.0,6143000.0,52,30,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
4,10308,42,cash,NaN,NaN,3642000.0,14464000.0,39,38,XNA,...,NaN,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN

In [5]:
df1 = pd.read_csv(r'D:\Portfolio\DS\Home Credit\Credit_home-analyst\data\raw\dazone_sample.csv')

In [6]:
df1 =df1.sort_values(by='customer_id').reset_index(drop=True)
df1.head(10)

,Unnamed: 0,customer_id,treatment,cash_sign_30d,card_sign_30d,min_sign_vol,avg_sign_vol,cnt_month_from_last_appl,cli_age,cli_job,...,max_cntr_len_fi_12m,amt_terminated_loan_12m,cnt_terminated_loan_12m,cnt_month_over3_credit_card_6m,cnt_noinsurance_loan_24m,cnt_earlyterminated_cash,cnt_earlyterminted_pos,cnt_inbound_tls_12m,cnt_month_from_first_transaction,cnt_month_from_last_transaction
0,123531,1,cash,0,0,4795000.0,7961000.0,2,35,OTHER,...,120.0,4990000.0,1.0,0.0,0.0,0,0,0.0,NaN,NaN
1,27728,2,card,0,0,2503000.0,4267000.0,14,44,SALESMAN,...,725.0,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
2,123532,3,card,0,0,9145000.0,9007000.0,8,52,FARMER,...,243.0,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
3,13942,4,cash,0,0,4765000.0,4906000.0,18,38,WORKER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
4,109999,5,card,0,0,5817000.0,38548000.0,38,46,OTHER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
5,55394,7,cash,0,0,2390000.0,5118000.0,16,27,WORKER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
6,27729,8,cash,0,0,4028000.0,21875000.0,41,26,WORKER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
7,82692,9,cash,0,0,22073000.0,21507000.0,119,21,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
8,96367,10,cash,0,0,10717000.0,10583000.0,60,30,OTHER,...,NaN,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN
9,0,11,cash,0,0,4141000.0,3986000.0,141,25,ENGINEER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN

In [7]:
df.shape

(34080, 45)

In [8]:
df1.shape

(136992, 45)

In [9]:
merged_df = df.merge(df1, on='customer_id', how='inner')
merged_df.head()

Empty DataFrame
Columns: [Unnamed: 0_x, customer_id, treatment_x, cash_sign_30d_x, card_sign_30d_x, min_sign_vol_x, avg_sign_vol_x, cnt_month_from_last_appl_x, cli_age_x, cli_job_x, cli_marital_status_x, cli_contact_region_level_x, cli_education_x, cli_emp_period_x, last_offer_limit_x, last_process_channel_x, f_approve_last_process_x, cnt_connected_tls_x, cnt_fail_tls_3m_x, f_appointment_3m_x, cnt_total_payment_x, risk_grp_x, cli_contact_region_population_grp_x, ratio_monthly_amt_l6m_vs_n6m_x, worst_credit_status_x, cnt_month_status1_x, ratio_vol_hcvn_cash_appl_12m_x, f_ever_default_x, ratio_conn_tls_weekend_12m_x, ratio_conn_tls_endmonth_12m_x, cnt_bank_inst_appl_12m_x, cnt_fi_inst_appl_12m_x, cnt_report_bank_6m_x, cnt_report_institution_12m_x, cnt_lender_has2pay_last_24m_x, max_cntr_len_fi_12m_x, amt_terminated_loan_12m_x, cnt_terminated_loan_12m_x, cnt_month_over3_credit_card_6m_x, cnt_noinsurance_loan_24m_x, cnt_earlyterminated_cash_x, cnt_earlyterminted_pos_x, cnt_inbound_tls_12m_x, cnt_month_from_first_transaction_x, cnt_month_from_last_transaction_x, Unnamed: 0_y, treatment_y, cash_sign_30d_y, card_sign_30d_y, min_sign_vol_y, avg_sign_vol_y, cnt_month_from_last_appl_y, cli_age_y, cli_job_y, cli_marital_status_y, cli_contact_region_level_y, cli_education_y, cli_emp_period_y, last_offer_limit_y, last_process_channel_y, f_approve_last_process_y, cnt_connected_tls_y, cnt_fail_tls_3m_y, f_appointment_3m_y, cnt_total_payment_y, risk_grp_y, cli_contact_region_population_grp_y, ratio_monthly_amt_l6m_vs_n6m_y, worst_credit_status_y, cnt_month_status1_y, ratio_vol_hcvn_cash_appl_12m_y, f_ever_default_y, ratio_conn_tls_weekend_12m_y, ratio_conn_tls_endmonth_12m_y, cnt_bank_inst_appl_12m_y, cnt_fi_inst_appl_12m_y, cnt_report_bank_6m_y, cnt_report_institution_12m_y, cnt_lender_has2pay_last_24m_y, max_cntr_len_fi_12m_y, amt_terminated_loan_12m_y, cnt_terminated_loan_12m_y, cnt_month_over3_credit_card_6m_y, cnt_noinsurance_loan_24m_y, cnt_earlyterminated_cash_y, cnt_earlyterminted_pos_y, cnt_inbound_tls_12m_y, cnt_month_from_first_transaction_y, cnt_month_from_last_transaction_y]
Index: []

[0 rows x 89 columns]

In [10]:
union_df = pd.concat([df, df1], ignore_index=True).drop_duplicates().reset_index(drop=True)
sorted_union_df = union_df.sort_values(by='customer_id').reset_index(drop=True)
sorted_union_df.head()

,Unnamed: 0,customer_id,treatment,cash_sign_30d,card_sign_30d,min_sign_vol,avg_sign_vol,cnt_month_from_last_appl,cli_age,cli_job,...,max_cntr_len_fi_12m,amt_terminated_loan_12m,cnt_terminated_loan_12m,cnt_month_over3_credit_card_6m,cnt_noinsurance_loan_24m,cnt_earlyterminated_cash,cnt_earlyterminted_pos,cnt_inbound_tls_12m,cnt_month_from_first_transaction,cnt_month_from_last_transaction
0,123531,1,cash,0.0,0.0,4795000.0,7961000.0,2,35,OTHER,...,120.0,4990000.0,1.0,0.0,0.0,0,0,0.0,NaN,NaN
1,27728,2,card,0.0,0.0,2503000.0,4267000.0,14,44,SALESMAN,...,725.0,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
2,123532,3,card,0.0,0.0,9145000.0,9007000.0,8,52,FARMER,...,243.0,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
3,13942,4,cash,0.0,0.0,4765000.0,4906000.0,18,38,WORKER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
4,109999,5,card,0.0,0.0,5817000.0,38548000.0,38,46,OTHER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN

In [11]:
sorted_union_df.to_csv(r'D:\Portfolio\DS\Home Credit\Credit_home-analyst\data\raw\dazone_sample_merged.csv', index=False)

In [12]:
df.isnull().mean()*100

Unnamed: 0                             0.000000
customer_id                            0.000000
treatment                              0.000000
cash_sign_30d                        100.000000
card_sign_30d                        100.000000
min_sign_vol                           0.440141
avg_sign_vol                           0.440141
cnt_month_from_last_appl               0.000000
cli_age                                0.000000
cli_job                                0.000000
cli_marital_status                    10.346244
cli_contact_region_level               0.466549
cli_education                          0.020540
cli_emp_period                        10.038146
last_offer_limit                       0.108568
last_process_channel                  29.465962
f_approve_last_process                28.923122
cnt_connected_tls                      0.000000
cnt_fail_tls_3m                       39.724178
f_appointment_3m                      56.399648
cnt_total_payment                      0.000000
risk_grp                               0.363850
cli_contact_region_population_grp      0.020540
ratio_monthly_amt_l6m_vs_n6m          82.611502
worst_credit_status                   28.656103
cnt_month_status1                     28.708920
ratio_vol_hcvn_cash_appl_12m          89.354460
f_ever_default                         5.534038
ratio_conn_tls_weekend_12m             0.002934
ratio_conn_tls_endmonth_12m            0.002934
cnt_bank_inst_appl_12m                28.465376
cnt_fi_inst_appl_12m                  28.465376
cnt_report_bank_6m                    28.465376
cnt_report_institution_12m            28.465376
cnt_lender_has2pay_last_24m           29.656690
max_cntr_len_fi_12m                   74.389671
amt_terminated_loan_12m               28.650235
cnt_terminated_loan_12m               28.650235
cnt_month_over3_credit_card_6m        28.708920
cnt_noinsurance_loan_24m               0.023474
cnt_earlyterminated_cash               0.000000
cnt_earlyterminted_pos                 0.000000
cnt_inbound_tls_12m                   39.724178
cnt_month_from_first_transaction      93.902582
cnt_month_from_last_transaction       93.902582
dtype: float64

In [13]:
df1.isnull().mean()*100

Unnamed: 0                            0.000000
customer_id                           0.000000
treatment                             0.000000
cash_sign_30d                         0.000000
card_sign_30d                         0.000000
min_sign_vol                          0.426302
avg_sign_vol                          0.426302
cnt_month_from_last_appl              0.000000
cli_age                               0.000000
cli_job                               0.000000
cli_marital_status                   10.188186
cli_contact_region_level              0.426302
cli_education                         0.030659
cli_emp_period                        9.930507
last_offer_limit                      0.081027
last_process_channel                 29.292221
f_approve_last_process               28.782703
cnt_connected_tls                     0.000000
cnt_fail_tls_3m                      39.660710
f_appointment_3m                     55.695223
cnt_total_payment                     0.001460
risk_grp                              0.352575
cli_contact_region_population_grp     0.030659
ratio_monthly_amt_l6m_vs_n6m         82.552996
worst_credit_status                  28.627219
cnt_month_status1                    28.679777
ratio_vol_hcvn_cash_appl_12m         89.469458
f_ever_default                        5.225853
ratio_conn_tls_weekend_12m            0.004380
ratio_conn_tls_endmonth_12m           0.004380
cnt_bank_inst_appl_12m               28.481955
cnt_fi_inst_appl_12m                 28.481955
cnt_report_bank_6m                   28.481955
cnt_report_institution_12m           28.481955
cnt_lender_has2pay_last_24m          29.570340
max_cntr_len_fi_12m                  74.072939
amt_terminated_loan_12m              28.619189
cnt_terminated_loan_12m              28.619189
cnt_month_over3_credit_card_6m       28.679777
cnt_noinsurance_loan_24m              0.033579
cnt_earlyterminated_cash              0.000000
cnt_earlyterminted_pos                0.000000
cnt_inbound_tls_12m                  39.660710
cnt_month_from_first_transaction     93.595976
cnt_month_from_last_transaction      93.595976
dtype: float64

In [14]:

cols_str = df.select_dtypes(include=['object', 'string']).columns
print(cols_str)

Index(['treatment', 'cli_job', 'cli_marital_status',
       'cli_contact_region_level', 'cli_education', 'last_process_channel',
       'risk_grp', 'cli_contact_region_population_grp'],
      dtype='object')

In [15]:
print(df[cols_str])

      treatment         cli_job cli_marital_status cli_contact_region_level  \
0          cash          WORKER                NaN                    North
1          cash           OTHER            Married                    North
2          card           OTHER            Married                  Central
3          cash           OTHER                NaN                    South
4          cash             XNA                NaN                  Central
...         ...             ...                ...                      ...
34075      card        ENGINEER            Married                    South
34076      card           OTHER             Single                    North
34077      card        SALESMAN            Married                    North
34078      cash           OTHER            Married                    South
34079      card  ADMINISTRATIVE            Married                  Central

           cli_education last_process_channel risk_grp  \
0              BACHELORS                    F        B
1                   PTCS                  NaN        E
2              BACHELORS                    H        C
3                   PTTH                    D        E
4                   PTCS                    D        C
...                  ...                  ...      ...
34075          BACHELORS                  NaN        E
34076          BACHELORS                  NaN        C
34077          BACHELORS                    D        C
34078  ELEMENTARY_SCHOOL                  NaN        E
34079          BACHELORS                  NaN        E

      cli_contact_region_population_grp
0                                 URBAN
1                                 RURAL
2                                 URBAN
3                             SUB_URBAN
4                                 RURAL
...                                 ...
34075                         SUB_URBAN
34076                         KEY_URBAN
34077                         KEY_URBAN
34078                             RURAL
34079                             URBAN

[34080 rows x 8 columns]

In [17]:
df["cli_marital_status"].unique()

array([nan, 'Married', 'XNA', 'Single', 'Divorced', 'Widowed',
       'Separated', 'Living with partner'], dtype=object)

In [18]:
df["cli_education"].unique()

array(['BACHELORS', 'PTCS', 'PTTH', 'ELEMENTARY_SCHOOL', 'MASTERS', nan],
      dtype=object)